
name: Benchmark

on:
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - ready_for_review

env:
  GITHUB_PR_NUMBER: ${{github.event.number}}

jobs:
  bench:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Benchmark
      id: bench
      run: |
        source .github/workflows/env.sh
        __group__ Init Environment
        ldmx use dev hdf5
        ldmx base ..
        __endgroup__
        bench ${GITHUB_REF#refs/heads/} 10 1 5 10 50 100 500 1000 5000 10000 50000 100000
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    -
      name: Install Plotting Requirements
      run: python -m pip install --upgrade matplotlib pandas
    -
      name: Plot
      run: python .github/workflows/plot.py ${BENCH_DATA_FILE}
      env:
        BENCH_DATA_FILE: ${{steps.bench.outputs.file}}
    -
      name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: Benchmark-Results-PR-${{github.event.number}}
        path: ${{steps.bench.outputs.dir}}
        if-no-files-found: error
