
name: Benchmark

on:
  push:
    - iss7-bench-pr
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - ready_for_review

env:
  GITHUB_PR_NUMBER: ${{github.event.number}}
  N_TRIALS: 10
  NEVENT_SAMPLE_POINTS: "1 5 10"

jobs:
  bench:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Benchmark
      id: bench
      run: |
        source .github/workflows/env.sh
        group Init Environment
        export GITHUB_BRANCH=${GITHUB_REF#refs/heads/}
        ldmx use dev hdf5
        ldmx base ..
        group Switch to ${GITHUB_BRANCH}
        git checkout ${GITHUB_BRANCH}
        group Configure Build
        ldmx cmake -B build/${GITHUB_BRANCH} -S . -DCMAKE_INSTALL_PREFIX=.container-install
        group Build and Install
        ldmx cmake --build build/${GITHUB_BRANCH} --target install
        group Build Test Module
        ldmx cmake -B build/${GITHUB_BRANCH}/test/module -S test/module \
          -DCMAKE_INSTALL_PREFIX=.container-install
        ldmx cmake --build build/${GITHUB_BRANCH}/test/module --target install
        group Run Benchmark
        run_bench ${GITHUB_BRANCH} ${N_TRIALS} ${NEVENT_SAMPLE_POINTS}
        group Delete Output Files
        rm -vr output
        group Post Outputs
        set_output dir ${BENCH_OUTPUT_DIR}
        set_output file ${BENCH_DATA_FILE}
        echo "::endgroup::"
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    -
      name: Install Plotting Requirements
      run: python -m pip install --upgrade matplotlib pandas
    -
      name: Plot
      run: python .github/workflows/plot.py ${BENCH_DATA_FILE}
      env:
        BENCH_DATA_FILE: ${{steps.bench.outputs.file}}
    -
      name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: Benchmark-Results-PR-${{github.event.number}}
        path: ${{steps.bench.outputs.dir}}
        if-no-files-found: error
