
name: CI

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/publish_docs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: get fire
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: test fire
      run: |
        source .github/workflows/env.sh
        group Init Environment
        ldmx use dev hdf5
        ldmx base ..
        group Configure Build
        ldmx cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/.container-install
        group Build fire
        ldmx cmake --build build
        group Test fire
        ldmx cmake --build build --target test
        group Install fire for Test Module
        ldmx cmake --build build/ --target install
        group Configure Test Module
        ldmx cmake -B build/test/module -S test/module \
          -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/.container-install
        group Build and Install Test Module
        ldmx cmake --build build/test/module --target install
        group Run Test Production
        ldmx fire test/module/prod.py 10
        group Run Test Reconstruction
        ldmx fire test/module/recon.py test/module/output/output_10.h5

