
name: CI

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/publish_docs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: get fire
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: test fire
      run: |
        source .github/workflows/env.sh
        __group__ Init Environment
        ldmx use dev hdf5
        ldmx base ..
        __endgroup__
        __group__ Configure Build
        ldmx cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/.container-install
        __endgroup__
        __group__ Build fire
        ldmx cmake --build build
        __endgroup__
        __group__ Test fire
        ldmx cmake --build build --target test
        __endgroup__
        __group__ Install fire for Test Module
        ldmx cmake --build build/ --target install
        __endgroup__
        __group__ Configure Test Module
        ldmx cmake -B build/test/module -S test/module \
          -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/.container-install
        __endgroup__
        __group__ Build and Install Test Module
        ldmx cmake --build build/test/module --target install
        __endgroup__
        __group__ Run Test Production
        ldmx fire test/module/prod.py 10
        __endgroup__
        __group__ Run Test Reconstruction
        ldmx fire test/module/recon.py test/module/output/output_10.h5
        __endgroup__

