
name: CI

on:
  push:
    tags:
      - '**'
    branches:
      - '**'
      - '!gh-pages'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - ready_for_review

jobs:
  test:
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix: #python3.6.9, python3.8.10
        os: [ ubuntu-18.04, ubuntu-20.04 ] #, macOS-10.15]
    steps:
    -
      name: install pytest requirements
      run: python3 -m pip install --upgrade pytest h5py
    -
      name: install dependencies ubuntu
      if: contains(matrix.os,'ubuntu')
      run: sudo apt-get update && sudo apt-get install libboost-all-dev libhdf5-dev 
    -
      name: install dependencies macos
      if: contains(matrix.os,'macOS')
      run: brew install boost hdf5
    -
      name: install HighFive
      run: |
        mkdir src
        wget -q -O - \
          https://github.com/BlueBrain/HighFive/archive/refs/tags/v2.3.1.tar.gz |\
          tar -xz --strip-components=1 --directory src
        mkdir src/build
        cd src/build
        cmake -DHIGHFIVE_EXAMPLES=OFF -DHIGHFIVE_UNIT_TESTS=OFF ..
        sudo make install
        cd -
        rm -rf src
    - 
      name: get fire
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: build fire
      run: |
        source .github/workflows/env.sh
        cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build
    -
      name: test fire
      working-directory: build
      run: ctest -VV
    -
      name: install fire
      working-directory: build
      run: make install
    -
      name: build test module
      run: |
        source .github/workflows/env.sh
        cmake -B build/test/module -S test/module -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build/test/module --target install
    -
      name: run test module
      run: |
        source .github/workflows/env.sh
        fire test/module/produce.py 10
        fire test/module/recon.py test/module/output_10.h5
  
  bench:
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      BENCH_OUTPUT_DIR: .github/workflows/output
      BENCH_DATA_FILE: .github/workflows/output/data.csv
      GITHUB_PR_NUMBER: ${{github.event.number}}
      N_TRIALS: 10
      NEVENT_SAMPLE_POINTS: "1 5 10 50 100 500 1000 5000 10000 100000 1000000"
    steps:
    -
      name: install pytest requirements
      run: python3 -m pip install --upgrade pytest h5py matplotlib pandas
    -
      name: install dependencies ubuntu
      run: sudo apt-get update && sudo apt-get install libboost-all-dev libhdf5-dev 
    -
      name: install HighFive
      run: |
        mkdir src
        wget -q -O - \
          https://github.com/BlueBrain/HighFive/archive/refs/tags/v2.3.1.tar.gz |\
          tar -xz --strip-components=1 --directory src
        mkdir src/build
        cd src/build
        cmake -DHIGHFIVE_EXAMPLES=OFF -DHIGHFIVE_UNIT_TESTS=OFF ..
        sudo make install
        cd -
        rm -rf src
    - 
      name: get fire
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: build fire
      run: |
        source .github/workflows/env.sh
        cmake -B build -S . -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build --target install
        cmake -B build/test/module -S test/module -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build/test/module --target install
    -
      name: bench developments
      run: |
        source .github/workflows/env.sh
        run_bench pr-${GITHUB_PR_NUMBER} ${N_TRIALS} ${NEVENT_SAMPLE_POINTS}
        group Cleanup
        git clean -xxfd -e ${BENCH_OUTPUT_DIR}
    -
      name: switch to trunk
      uses: actions/checkout@v2
      with:
        ref: 'trunk'
        submodules: 'recursive'
        clean: false
    -
      name: build fire
      run: |
        source .github/workflows/env.sh
        cmake -B build -S . -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build --target install
        cmake -B build/test/module -S test/module -DCMAKE_INSTALL_PREFIX=${FIRE_INSTALL_PREFIX}
        cmake --build build/test/module --target install
    -
      name: bench trunk
      run: |
        source .github/workflows/env.sh
        run_bench trunk ${N_TRIALS} ${NEVENT_SAMPLE_POINTS}
        group Cleanup
        git clean -xxfd -e ${BENCH_OUTPUT_DIR}
    -
      name: Plot
      run: python3 .github/workflows/plot.py ${BENCH_DATA_FILE}
    -
      name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: Benchmark-Results-PR-${{github.event.number}}
        path: ${{env.BENCH_OUTPUT_DIR}}
        if-no-files-found: error

  update-docs:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive' # for doxygen-awesome-css
      -
        name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - 
        name: install doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.2.linux.bin.tar.gz
          ln -s doxygen-1.9.2/bin/doxygen doxygen
      -
        name: install sphinx
        run: python -m pip install --upgrade Sphinx
      - 
        name: set version
        run: |
          _version_tag=$(git describe --tags)
          _cmake_version=$(grep "^[ \t]*VERSION" CMakeLists.txt | sed 's/[^.0-9]*//g')
          if [[ "${_version_tag}" == "v${_cmake_version}" ]]; then
            echo "::error::Git version v${_version_tag} does not match CMake version ${_cmake_version}"
            exit 1
          fi
          echo ${_version_tag}
          echo "PROJECT_NUMBER = ${_version_tag}" >> docs/doxyfile
          echo "release = '${_version_tag}'" >> docs/python/conf.py
      - 
        name: run doxygen
        run: ./doxygen docs/doxyfile
      -
        name: run sphinx
        run: sphinx-build docs/python docs/html/python
      - 
        name: publish generated content
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.LDMX_ORG_TOKEN }}
