
name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*'
    paths-ignore:
      - '**.md'

# workflow consists of one building and testing job
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: get fire
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: test fire
      run: |
        source .github/rootless-env.sh
        echo "::group::Setup Environment"
        ldmx use dev hdf5
        ldmx base ..
        echo "::endgroup::"
        echo "::group::Configure Build"
        ldmx cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${LDMX_BASE}/.container-install
        echo "::endgroup::"
        echo "::group::Build Tests"
        cd build
        ldmx make test
        echo "::endgroup::"
        echo "::group::Test CMake Loading in Another Module"
        ldmx make install
        cd ../test/module
        ldmx cmake -B build -S .
